### ISSUE TITLE
Crash on launch with quilt loader

### ISSUE THREAD

**Issue by JieningYu** [paulevsGitch/EdenRing#27]
`Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'edenring'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:62)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:60)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:45)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:32)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_3614 net.fabricmc.fabric.mixin.object.builder.AbstractBlockSettingsAccessor.getMaterial()'
	at paulevs.edenring.registries.EdenBlocks.lambda$init$2(EdenBlocks.java:178)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at paulevs.edenring.registries.EdenBlocks.init(EdenBlocks.java:176)
	at paulevs.edenring.EdenRing.onInitialize(EdenRing.java:47)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:52)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:32)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:58)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:62)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:60)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:45)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:32)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Mac OS X (x86_64) version 12.2
	Java Version: 18, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), BellSoft
	Memory: 643341576 bytes (613 MiB) / 1568669696 bytes (1496 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 70 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel Iris Pro
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x0d26
	Graphics card #0 versionInfo: Revision ID: 0x0008
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 19456.00
	Virtual memory used (MB): 13532.16
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 2350.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	QuiltedFabricAPI: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		bclib: BCLib 1.4.5
		edenring: EdenRing 0.5.1
		java: OpenJDK 64-Bit Server VM 18
		minecraft: Minecraft 1.18.2
		quilt_base: Quilt Base API 1.1.0-beta.8+1.18.2
		quilt_block_extensions: Quilt Block Extensions API 1.1.0-beta.8+1.18.2
		quilt_client_command: Quilt Client Command API 1.1.0-beta.8+1.18.2
		quilt_command: Quilt Command API 1.1.0-beta.8+1.18.2
		quilt_crash_info: Quilt Crash Info 1.1.0-beta.8+1.18.2
		quilt_dimension: Quilt Dimension API 1.1.0-beta.8+1.18.2
		quilt_item_group: Quilt Item Group API 1.1.0-beta.8+1.18.2
		quilt_item_setting: Quilt Item Setting API 1.1.0-beta.8+1.18.2
		quilt_lifecycle_events: Quilt Lifecycle Events 1.1.0-beta.8+1.18.2
		quilt_loader: Quilt Loader 0.16.0-beta.16
		quilt_networking: Quilt Networking 1.1.0-beta.8+1.18.2
		quilt_recipe: Quilt Recipe API 1.1.0-beta.8+1.18.2
		quilt_registry: Quilt Registry API 1.1.0-beta.8+1.18.2
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 1.1.0-beta.8+1.18.2
		quilt_resource_loader: Quilt Resource Loader 1.1.0-beta.8+1.18.2
		quilt_tags: Quilt Tags API 1.1.0-beta.8+1.18.2
		quilt_tooltip: Quilt Tooltip API 1.1.0-beta.8+1.18.2
		quilted_fabric_api: Quilted Fabric API 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_api_base: Quilted Fabric API Base 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_command_api_v1: Quilted Fabric Command API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_commands_v0: Quilted Fabric Commands (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_containers_v0: Quilted Fabric Containers (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_events_lifecycle_v0: Quilted Fabric Events Lifecycle (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_keybindings_v0: Quilted Fabric Key Bindings (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_loot_tables_v1: Quilted Fabric Loot Tables (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_networking_v0: Quilted Fabric Networking (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_renderer_registries_v1: Quilted Fabric Renderer Registries (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_rendering_v0: Quilted Fabric Rendering (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 1.0.0-beta.12+0.51.1-1.18.2
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 1.0.0-beta.12+0.51.1-1.18.2
	Launched Version: PolyMC
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'
	Type: Client (map_client.txt)
	CPU: <unknown>`

**Comment by JieningYu** [comment]
caused by eden ring because removes only eden ring(keeps bclib) is fine.

**Comment by paulevsGitch** [comment]
> NoSuchMethodError: 'net.minecraft.class_3614 net.fabricmc.fabric.mixin.object.builder.AbstractBlockSettingsAccessor.getMaterial()

Looks like a problem in Quilt with missing Fabric class. It is not related to Eden Ring
