### ISSUE TITLE
[bug] Gravity Compressor

### ISSUE THREAD

**Issue by BetaATG** [paulevsGitch/EdenRing#30]
When i **place** the **Gravity Compressor** the game **crashes** and the world is **not playable anymore**. It happened on a server with my friend and it crashed both of us.

**Comment by paulevsGitch** [comment]
Please provide your logs

**Comment by ImpSpy2** [comment]
Same issue here, sometimes when I place the block the game crashes other times I can place the block but activating it with redstone or right clicking it causes the crash.

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 02/06/2022, 16:02
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property class_2746{name=extended, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{edenring:gravity_compressor}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.minecraft.class_2246.method_26125(class_2246.java:99)
	at net.minecraft.class_4970$class_4971.method_26228(class_4970.java:947)
	at net.minecraft.class_5329.method_29285(class_5329.java:91)
	at net.minecraft.class_5329.computeNext(class_5329.java:19)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at net.minecraft.class_1941.method_39454(class_1941.java:90)
	at net.minecraft.class_746.method_30674(class_746.java:475)
	at net.minecraft.class_746.method_30673(class_746.java:440)
	at net.minecraft.class_746.method_6007(class_746.java:712)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1657.method_5773(class_1657.java:275)
	at net.minecraft.class_746.method_5773(class_746.java:212)
	at net.minecraft.class_638.method_18646(class_638.java:217)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)
	at net.minecraft.class_310.method_1574(class_310.java:1761)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.minecraft.class_2246.method_26125(class_2246.java:99)
	at net.minecraft.class_4970$class_4971.method_26228(class_4970.java:947)
	at net.minecraft.class_5329.method_29285(class_5329.java:91)
	at net.minecraft.class_5329.computeNext(class_5329.java:19)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at net.minecraft.class_1941.method_39454(class_1941.java:90)
	at net.minecraft.class_746.method_30674(class_746.java:475)
	at net.minecraft.class_746.method_30673(class_746.java:440)
	at net.minecraft.class_746.method_6007(class_746.java:712)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1657.method_5773(class_1657.java:275)
	at net.minecraft.class_746.method_5773(class_746.java:212)
	at net.minecraft.class_638.method_18646(class_638.java:217)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 182
	Entity Name: player1
	Entity's Exact location: -104.53, 130.00, 130.90
	Entity's Block location: World: (-105,130,130), Section: (at 7,2,2 in -7,8,8; chunk contains blocks -112,0,128 to -97,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.06, -0.08, 0.10
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)
	at net.minecraft.class_310.method_1574(class_310.java:1761)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['player1'/182, l='ClientLevel', x=-104.53, y=130.00, z=130.90]]
	Chunk stats: 1849, 280
	Level dimension: edenring:edenring
	Level spawn location: World: (0,66,0), Section: (at 0,2,0 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2101 game time, 2101 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.17.4-1-default
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1231110056 bytes (1174 MiB) / 2717908992 bytes (2592 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 16640.00
	Graphics card #0 deviceId: 0x73df
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 48015.73
	Virtual memory used (MB): 7685.82
	Swap memory total (MB): 32009.69
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		bclib: BCLib 1.4.7
		edenring: EdenRing 0.5.1
		fabric: Fabric API 0.53.4+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.1+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.5+d82b939260
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.16+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.0+85719ab760
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.12+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.4+d8d7804a60
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.1+81ea5b3c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
			fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.1+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.0+2afceb2960
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.2+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.14.6
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.2
	Launched Version: fabric-loader-0.14.6-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon RX 6700 XT (navy_flounder, LLVM 14.0.0, DRM 3.44, 5.17.4-1-default) GL version 4.6 (Core Profile) Mesa 22.0.2, AMD
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor
	Server Running: true
	Player Count: 1 / 8; [class_3222['player1'/182, l='ServerLevel[New World]', x=-104.53, y=130.00, z=130.90]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental

**Comment by paulevsGitch** [comment]
I think I know the reason - some versions of Fabric API can copy blockstate properties together with all other values (and looks like this bug is unstable, was faced it before). Try to use 0.48 v. of API (the mod uses it), I will replace constructor parameter with direct material and values (which should fix it)
![image](https://user-images.githubusercontent.com/17707380/173177503-b8d7e896-2324-4d18-b666-7cedf14caf33.png)
